[package]
name = "immutable_storage"
version = "0.0.1"

[dependencies]
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "devnet" }

[addresses]
immutable_storage = "0x0"